### ISSUE TITLE
`which-key` falling off-screen on narrow monitors

### ISSUE THREAD

**Issue by richarddewit** [dvcrn/proton#182]
My screens are in portrait mode so quite narrow (1200x1920, minus treeview is something like 980px). Could the `which-key` panel be scaled so all commands fit on screen? Maybe with a ratio or media queries?

![2016-03-29-102404_983x153_scrot](https://cloud.githubusercontent.com/assets/7933750/14102019/7d5b4a76-f598-11e5-8c13-aeb13f4bae68.png)

---

**Edit**
For now I'm using my stylesheet to fit stuff on my screen:

``` less
.proton-which-key {
  font-size: 11px;

  .flex-container {
    .flex-item {
      width: 250px;
    }
  }
}
```

![2016-03-29-114132_978x146_scrot](https://cloud.githubusercontent.com/assets/7933750/14104026/4073b476-f5a3-11e5-8409-fc75e2bc6ec2.png)
