### ISSUE TITLE
dot-symbol in config-key

### ISSUE THREAD

**Issue by gabor** [dvcrn/proton#255]
i'm trying to convert the following code from `config.cson` to `.proton`:

```
".js.source":
  editor:
    tabLength: 2
```

i tried to simply do
```
[".js.source.editor.tabLength" 2]
```

but proton uses `.` to split the key it seems, so it becomes
```
  ""
    js:
      source:
        editor:
          tabLength: 2
```

any ideas what to do here? is there perhaps a way to escape the `.` ?
