### ISSUE TITLE
Allow setting settings by syntax

### ISSUE THREAD

**Issue by spencerlyon2** [dvcrn/proton#38]
In my config I have things like:

```
".coffee.source":
  editor:
    tabLength: 2
".bibtex.text":
  editor:
    tabLength: 2
".julia.source":
  editor:
    tabLength: 2
  "multi-wrap-guide":
    columns: [
      72
      80
      92
    ]
```

If I try to add something like `[".julia.source.editor.tabLength" 2]` in my `~/.proton` I get 

```
  "":
    julia:
      source:
        editor:
          tabLength: 2
```

I think we just need to special case a leading `.` in the config string when parsing configs
